spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:brambledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.bramble.novel: INFO
    org.springframework.security: WARN
